networks:
  symfony:
    driver: bridge

volumes:
  symfony_db:

services:
  apache:
    container_name: librarie_app_apache
    build: ./docker/build/apache
    ports:
      - '8010:80'
    depends_on:
      - mysql
      - mailpit
    volumes:
      - './docker/etc/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf:ro'
      - './docker/etc/apache/default-ssl.conf:/etc/apache2/sites-enabled/default-ssl.conf'
      - './docker/etc/php/php.ini:/usr/local/etc/php/php.ini'
      - './docker/etc/apache/ssl/:/etc/apache2/conf/ssl'
      - './app/symfony:/var/www/symfony'
    networks:
      - symfony
  mysql:
    container_name: librarie_app_mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - './docker/etc/mysql/my.cnf:/etc/mysql/conf.d/my.cnf'
      - 'symfony_db:/var/lib/mysql:cached'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: librarie_app
    networks:
      - symfony

  phpmyadmin:
    container_name: librarie_app_phpmyadmin
    ports:
      - '8001:80'
    image: nazarpc/phpmyadmin
    networks:
      - symfony
    depends_on:
      - mysql

  mailpit:
    image: axllent/mailpit
    container_name: librarie_app_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - symfony
